ADD file:c03517c5ddbed4053165bfdf984b27a006fb5f533ca80b5798232d96df221440 in / 
CMD ["bash"]
RUN set -eux;  apt-get update;  apt-get install -y --no-install-recommends   ca-certificates   curl   netbase   wget  ;  rm -rf /var/lib/apt/lists/*
RUN set -ex;  if ! command -v gpg > /dev/null; then   apt-get update;   apt-get install -y --no-install-recommends    gnupg    dirmngr   ;   rm -rf /var/lib/apt/lists/*;  fi
RUN apt-get update && apt-get install -y --no-install-recommends   git   mercurial   openssh-client   subversion     procps  && rm -rf /var/lib/apt/lists/*
RUN set -eux;  apt-get update;  apt-get install -y --no-install-recommends   bzip2   unzip   xz-utils     fontconfig libfreetype6     ca-certificates p11-kit  ;  rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/local/openjdk-8
RUN { echo '#/bin/sh'; echo 'echo "$JAVA_HOME"'; } > /usr/local/bin/docker-java-home && chmod +x /usr/local/bin/docker-java-home && [ "$JAVA_HOME" = "$(docker-java-home)" ] # backwards compatibility
ENV PATH=/usr/local/openjdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LANG=C.UTF-8
ENV JAVA_VERSION=8u312
RUN set -eux;   arch="$(dpkg --print-architecture)";  case "$arch" in   'amd64')    downloadUrl='https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jdk_x64_linux_8u312b07.tar.gz';    ;;   'arm64')    downloadUrl='https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jdk_aarch64_linux_8u312b07.tar.gz';    ;;   *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;;  esac;   wget --progress=dot:giga -O openjdk.tgz "$downloadUrl";  wget --progress=dot:giga -O openjdk.tgz.asc "$downloadUrl.sign";   export GNUPGHOME="$(mktemp -d)";  gpg --batch --keyserver keyserver.ubuntu.com --recv-keys EAC843EBD3EFDB98CC772FADA5CD6035332FA671;  gpg --batch --keyserver keyserver.ubuntu.com --keyserver-options no-self-sigs-only --recv-keys CA5F11C6CE22644D42C6AC4492EF8D39DC13168F;  gpg --batch --list-sigs --keyid-format 0xLONG CA5F11C6CE22644D42C6AC4492EF8D39DC13168F   | tee /dev/stderr   | grep '0xA5CD6035332FA671'   | grep 'Andrew Haley';  gpg --batch --verify openjdk.tgz.asc openjdk.tgz;  gpgconf --kill all;  rm -rf "$GNUPGHOME";   mkdir -p "$JAVA_HOME";  tar --extract   --file openjdk.tgz   --directory "$JAVA_HOME"   --strip-components 1   --no-same-owner  ;  rm openjdk.tgz*;   {   echo '#!/usr/bin/env bash';   echo 'set -Eeuo pipefail';   echo 'trust extract --overwrite --format=java-cacerts --filter=ca-anchors --purpose=server-auth "$JAVA_HOME/jre/lib/security/cacerts"';  } > /etc/ca-certificates/update.d/docker-openjdk;  chmod +x /etc/ca-certificates/update.d/docker-openjdk;  /etc/ca-certificates/update.d/docker-openjdk;   find "$JAVA_HOME/lib" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf;  ldconfig;   javac -version;  java -version
RUN mkdir /app
ADD file:0b7ecbae98cbb5712188f23a3e982d76a483ef1c53affcb061e4deb6f3228beb in /app 